---
- name: Delete | import common tasks
  tags:
    - glance
    - openstack
  ansible.builtin.import_tasks: "common.yml"

- name: Delete | remove packages
  tags:
    - heat
    - openstack
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop: "{{ packages }}"
  become: true

- name: DB | delete database
  tags:
    - heat
    - openstack
  community.mysql.mysql_db:
    login_unix_socket: "{{ mariadb_service_socket }}"
    login_user: "root"
    login_password: "{{ mariadb_root_password }}"
    name: "{{ os_service_name }}"
    state: absent
  delegate_to: "{{ groups['mariadb'][0] }}"
  run_once: true
  no_log: true

- name: Delete | delete config directory
  tags:
    - heat
    - openstack
  ansible.builtin.file:
    path: "{{ os_conf_dir }}"
    state: absent
  become: true
...
